from .GetAllProductQuery import GetAllProductQuery
from .GetProductByIdQuery import GetProductByIdQuery
from .CreateProductQuery import CreateProductQuery
from .UpdateProductQuery import UpdateProductQuery
from .DeleteProductQuery import DeleteProductQuery