from .LoginQuery import LoginQuery
from .RegiserQuery import RegisterQuery
from .GetUserDetailQuery import GetUserDetailQuery
from .UpdateUserQuery import UpdateUserQuery
from .LogoutQuery import LogoutQuery
from .GetNewAccessTokenQuery import GetNewAccessTokenQuery
from .GetAllWarehousesQuery import GetAllWarehousesQuery
from .GetAllUsersQuery import GetAllUsersQuery
from .ActivateUserQuery import ActivateUserQuery
from .DeactivateUserQuery import DeactivateUserQuery
from .DashboardStatsQuery import DashboardStatsQuery