version: "3.9"

networks:
  shared-network:
    external: true

services:
  gateway:
    image: nginx:alpine
    restart: always
    container_name: gateway-service
    ports:
      - "8080:80"
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shared-network