version: "3.9"

services:
  gateway:
    image: nginx:alpine
    restart: always
    container_name: gateway-service
    ports:
      - "8080:80"
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shared-network
    depends_on:
      - product
  product:
    build:
      context: ./shared
      dockerfile: Dockerfile.dev
    restart: always
    container_name: product-service
    environment:
      - ENV=development
      - SERVICE_NAME=product
    volumes:
      - ./product:/usr/src/app
    command: ["/entrypoint.sh", "uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0", "--reload", "--reload-dir", "/usr/src/app"]
    networks:
      - shared-network
  supplier:
    build:
      context: ./shared
      dockerfile: Dockerfile.dev
    restart: always
    container_name: supplier-service
    environment:
      - ENV=development
      - SERVICE_NAME=supplier
    volumes:
      - ./supplier:/usr/src/app
    command: ["/entrypoint.sh", "uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0", "--reload", "--reload-dir", "/usr/src/app"]
    networks:
      - shared-network

  user:
    build:
      context: ./shared
      dockerfile: Dockerfile.dev
    restart: always
    container_name: user-service
    environment:
      - ENV=development
      - SERVICE_NAME=user
    volumes:
      - ./user:/usr/src/app
    command: ["/entrypoint.sh", "uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0", "--reload", "--reload-dir", "/usr/src/app"]
    networks:
      - shared-network

  order:
    build:
      context: ./shared
      dockerfile: Dockerfile.dev
    restart: always
    container_name: order-service
    environment:
      - ENV=development
      - SERVICE_NAME=order
    volumes:
      - ./order:/usr/src/app
    command: ["/entrypoint.sh", "uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0", "--reload", "--reload-dir", "/usr/src/app"]
    networks:
      - shared-network

  customer:
    build:
      context: ./shared
      dockerfile: Dockerfile.dev
    restart: always
    container_name: customer-service
    environment:
      - ENV=development
      - SERVICE_NAME=customer
    volumes:
      - ./customer:/usr/src/app
    command: ["/entrypoint.sh", "uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0", "--reload", "--reload-dir", "/usr/src/app"]
    networks:
      - shared-network

networks:
  shared-network:
    external: true